### PR TITLE
Update custom-currency.php

### PR DESCRIPTION
**Pull request by ibndawood**
I believe the function should return symbol and not currency.

### CODE REVIEW

**Comment by DevinWalker** [comment]
@mathetos did you get this snippet from our docs? If so, we should update them...

**Comment by DevinWalker** [comment]
@ibndawood can you explain the problem / solution here so I can understand the PR

**Comment by ibndawood** [comment]
@DevinWalker - If you look at this https://github.com/WordImpress/Give/blob/3eafebbfc912cd861e4a0b6645a6039bfe4ef643/includes/misc-functions.php#L131

The filters pass 2 arguments `$symbol` and `$currency` in this order but In the snippet :
*  in the add_filter it says it accepts 3 arguments : https://github.com/WordImpress/Give-Snippet-Library/blob/master/admin-functions/custom-currency.php#L34
*  the filter function `add_colon_symbol` has only one param which is `$currency` : https://github.com/WordImpress/Give-Snippet-Library/blob/master/admin-functions/custom-currency.php#L36 but it should by `$symbol` and `$currency`
* and it returns `$currency` https://github.com/WordImpress/Give-Snippet-Library/blob/master/admin-functions/custom-currency.php#L44 when it should be returning `$symbol`.

Those were the changes I made.

**Comment by mathetos** [comment]
@DevinWalker I wrote that code. @ibndawood is totally right, even though my code "worked" his corrections are more appropriate. 

Merged. Thanks!

**Pull request merged**
