### PR TITLE
Clarify and expand

### PR DESCRIPTION
**Pull request by Benunc**

### CODE REVIEW

**Comment by DevinWalker** [comment]
Can you change that into `elseif`?

**Comment by Benunc** [comment]
yes, changed.

**Comment by DevinWalker** [comment]
@Benunc there's a typo in it and please remove the spacing before the if statements last bracket and the elseif.

**Comment by Benunc** [comment]
heh. you mean esleif is not the same as elseif? 🚥

**Comment by DevinWalker** [comment]
👍

**Pull request merged**
