### PR TITLE
Create magic-tag.php

### PR DESCRIPTION
**Pull request by rumspeed**
It's Magic!

### CODE REVIEW

**Comment by mathetos** [comment]
Hey @rumspeed 

Looks interesting. By "magic" you just mean that the content of the tag will only output if the donation comes from a specific form, right?

If so, that's how all our tags work. If there is no content submitted to a specific email tag, nothing outputs at all. 

Clarify a bit for me.

**Comment by DevinWalker** [comment]
Bump

**Comment by Benunc** [comment]
The way I understand his tag's magic is that he can put one tag that pulls from several different fields, depending on the form.

It is an alternative method to solving the problem of sending form-specific emails, by being able to put a tag in the email that chooses from different field data depending on the form. With this method, you don't need an extra email template, because the tag is doing the work for you.

**Comment by DevinWalker** [comment]
Looks like something we can work with... I'm merging it.

**Pull request merged**
